apiVersion: apps/v1
kind: Deployment
metadata:
  name: paper-cranes-depl
spec:
  replicas: 1
  selector:
    matchLabels:
      app: paper-cranes
  template:
    metadata:
      labels:
        app: paper-cranes
    spec:
      containers:
        - name: paper-cranes
          image: lanyanxi/paper-cranes
          env:
            - name: JWT_SECRET
              valueFrom:
                secretKeyRef:
                  name: jwt-secret
                  key: JWT_SECRET
            - name: NATS_CLIENT_ID
              valueFrom:
                fieldRef:
                  fieldPath: metadata.name
            - name: NATS_URL
              value: http://nats-service:4222
            - name: NATS_CLUSTER_ID
              value: letitfly
            - name: MONGO_CONNECTION_URI
              value: "mongodb://paper-cranes-mongo-service:27017/paper-cranes"

---
apiVersion: v1
kind: Service
metadata:
  name: paper-cranes-service
spec:
  selector:
    app: paper-cranes
  ports:
    - name: paper-cranes
      protocol: TCP
      port: 3000
      targetPort: 3000
